### ISSUE TITLE
Missing : send_raw_command

### ISSUE THREAD

**Issue by jokok0** [Doubledom45/HA_RFPLAYER#2]
Hello
I'm from a beta deposit and I switched for this one because old one was outdated
I used to use send_raw_command to send specific command to my somfy store

Here is the configuration I used:

```
volet_somfy_cuisine:
        unique_id: "cover.rfplayer.somfy.cuisine"
        device_class: shutter
        friendly_name: "Volet Cuisine"
        optimistic: true
        open_cover:
          service: rfplayer.send_command
          data:
              command: "ON"
              protocol: RTS
              device_address: A4
        close_cover:
          service: rfplayer.send_command
          data:
              command: "OFF"
              protocol: RTS
              device_address: A4
        stop_cover:
          service: rfplayer.send_raw_command
          data:
              command: "ZIA++DIM A4 RTS %4"
```

But this command is no longer available, and I can't replace with send_command

Service described here : https://github.com/crazymikefra/HA_RFPlayer/blob/main/custom_components/rfplayer/services.yaml

Implemented here https://github.com/crazymikefra/HA_RFPlayer/issues/13#issuecomment-1520503133 

Is there possible to restore this feature ?
